### ISSUE TITLE
-chunk 功能运行失败

### ISSUE THREAD

**Issue by hundan2020** [LandGrey/pydictor#3]
```python pydictor.py -chunk abc ABC 666 . _ @ "'" --head a --tail 123 --encode md5```
返回
```
D:\OkMyTools\pydictor\pydictor>python pydictor.py -chunk abc ABC 666 . _ @ "'" --head a --tail 123 --encode md5
                              _ _      _
              _ __  _   _  __| (_) ___| |_ ___  _ __
             | '_ \| | | |/ _` | |/ __| __/ _ \| '__|
             | |_) | |_| | (_| | | (__| || (_) | |
             | .__/ \__, |\__,_|_|\___|\__\___/|_|
             |_|    |___/                            2.0.3#dev

Traceback (most recent call last):
  File "pydictor.py", line 91, in <module>
    get_chunk_dic(pyoptions.args_chunk)
  File "D:\OkMyTools\pydictor\pydictor\core\CHUNK.py", line 34, in get_chunk_dic
    special_types=pyoptions.special_types,
  File "D:\OkMyTools\pydictor\pydictor\lib\fun\filter.py", line 206, in filterforfun
    item = headtail_filter(item, head=head, tail=tail)
  File "D:\OkMyTools\pydictor\pydictor\lib\fun\filter.py", line 26, in headtail_filter
    return head + item + tail
TypeError: cannot concatenate 'str' and 'tuple' objects
```
Python 2.7
windows10 x64，家庭中文版，版本1607

**Comment by LandGrey** [comment]
thanks, bug has fixed: [here](https://github.com/LandGrey/pydictor/commit/5ad2b0aba9f6c6b2b7222ff373efdd4fcdca5fa9)
